#!/bin/bash
#write by shuaili

function fb()
{
  dir=$1
  max=$2
  while read size subdir
  do
    if [[ $size -gt $max ]]
    then
      echo $size $subdir
      fb $subdir $max
    fi
  done < <(du -s ${dir%/}/* 2>/dev/null)

}

max=${2:-"2000"}
dir=${1:-"/"}
let max=$max*1000
fb $dir $max
