#!/usr/bin/env python

import json
import pycurl
import httplib
import sys
import commands

if len(sys.argv) == 4:
    url_pre = sys.argv[1]
    path = sys.argv[2]
    key = sys.argv[3]
else:
    print "please input three arg"
    sys.exit(25)

url = url_pre+path
cmd = "curl " + url + " 2>/dev/null"
status, output = commands.getstatusoutput(cmd)
#print output
dic = json.loads(output)

for k in key.split("/"):
    dic = dic[k]
    if k == key.split("/")[-1]:
	if type(dic) == type([]):
            for i in dic:
                print i
        else:
            print dic
