#!/bin/bash
#write by shuaili

while getopts ":b:m:p:irdlchv" optname
do
    case "$optname" in
      "b")
        basefile=$OPTARG
        ;;
      "m")
        groupname=$OPTARG
        ;;
      "d")
        rmpid=true
        ;;
      "r")
        rm_cg=true
        ;;
      "p")
        procpid=$OPTARG
        ;;
      "l")
        list_cg=true
        ;;
      "c")
        create_cg=true
        ;;
      "h")
        echo "help:$0 "
        ;;
      "v")
        debuglabel=true
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        ;;
      *)
        echo "Unknown error while processing options"
        ;;
    esac
done

[[ $basefile ]] && base=$(cat basefile)
[[ $basefile ]] || base="
cpu.shares=128
memory.limit_in_bytes=10000000000
blkio.weight=100
"

for i in $base
do
  pra=${i%%=*}
  value=${i#*=}
  maxv=$(cgget -r $pra / | grep -v "/:" |awk '{print $NF}')
  let ts=$maxv/$value
  [[ $maxts ]] || maxts=$ts
  [[ $ts -lt $maxts ]] && maxts=$ts
done
[[ $debuglabel ]] && echo maxts is $maxts

if [[ $create_cg ]]
then
  i=1
  while [[ $i -le $maxts ]]
  do
    gn=${i}_times
    for j in $base
    do
      pra=${j%%=*}
      cg=${pra%%.*}
      let value=${j#*=}*$i
      cgcreate -g $cg:$gn
      cgset -r $pra=$value /$gn
    done
    let i=i*2
  done
fi

if [[ $list_cg ]]
then
  echo -e -n "root_cg\t\t"
  for j in $base
  do
    pra=${j%%=*}
    cg=${pra%%.*}
    dis=$(cgget -r $pra / 2>/dev/null|grep -v "/"|sed -e "s/ //")
    echo -e -n "$dis\t\t"
  done
  echo

  i=1
  while [[ $i -le $maxts ]]
  do
    gn=${i}_times
    echo -e -n "$gn\t\t"
    for j in $base
    do
      pra=${j%%=*}
      cg=${pra%%.*}
      value=${j#*=}
      dis=$(cgget -r $pra /$gn 2>/dev/null|grep -v "$gn"|sed -e "s/ //")
      echo -e -n "$dis\t\t"
    done
    echo
    if [[ $debuglabel ]]
    then
      grep "$gn" /proc/*/cgroup |awk -F '/' '{print $3}'|sort |uniq 
    fi
    let i=i*2
  done
fi

if [[ $rm_cg ]]
then
  i=1
  while [[ $i -le $maxts ]]
  do
    gn=${i}_times
    for j in $base
    do
      pra=${j%%=*}
      cg=${pra%%.*}
      value=${j#*=}
      cgdelete -r $cg:$gn
    done
    echo
    let i=i*2
  done
fi

if [[ $procpid ]]
then
  pidlist=`ps -eLf |awk -v pid=$procpid '{if($2==pid){print $4}}'`
fi


if [[ $groupname ]]
then
  for i in $base
  do
    pra=${i%%=*}
    cg=${pra%%.*}
    value=${i#*=}
    cgclassify -g $cg:$groupname --sticky $procpid $pidlist
  done
fi

if [[ $rmpid ]]
then
  for i in $base
  do
    pra=${i%%=*}
    cg=${pra%%.*}
    cgclassify -g $cg:/ --sticky $procpid $pidlist
  done
fi

