#!/bin/bash
#write by shuaili


while getopts ":m:d:p:lchv" optname
do
    case "$optname" in
      "m")
        groupname=$OPTARG
        ;;
      "d")
        rmpid=true
        ;;
      "p")
        procpid=$OPTARG
        ;;
      "l")
        list_cg=true
        ;;
      "c")
        create_cg=true
        ;;
      "h")
        echo "help:$0 "
        ;;
      "v")
        debuglabel=true
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        ;;
      *)
        echo "Unknown error while processing options"
        ;;
    esac
done

base="
cpu.shares=256
blkio.weight=128
"

for i in $base
do
  pra=${i%%=*}
  value=${i#*=}
  maxv=$(cgget -r $pra / | grep -v "/:" |awk '{print $NF}')
  let ts=$maxv/$value
  [[ $mints ]] || mints=$ts
  [[ $ts -lt $mints ]] && mints=$ts
done

echo mints is $mints
