#!/bin/env python
#use sar data create jpg
#write by lishuai

import cgi, os
import sys, re
import time
import commands
import random
import cgitb; cgitb.enable()

form = cgi.FieldStorage()
#status, output = commands.getstatusoutput("")


def psg():
    'create a jpg file for sar use gnuplot'
    
    status, output = commands.getstatusoutput("mkdir tmp;mkdir img")
    status, output = commands.getstatusoutput("LANG=C;sar -f /var/log/sa/sa15 |grep -P '\d\d:\d\d:\d\d' |grep -v '%' |awk '{print $1,$8}'>tmp/test.sar")
    #status, output = commands.getstatusoutput("LANG=C;sar -f /var/log/sa/sa27 |grep -P '\d\d:\d\d:\d\d' |grep -v '%' |awk '{print $1,$8}'>tmp/test.sar")



def ph():
    print '''
<html>
  <body>
    <form enctype="multipart/form-data" action="/cgi-bin/psg" method="post">
      <p>date: <input type="text" name="date"/>
      <select name="type">
                <option value="cpu">cpu</option>
                <option value="mem">mem</option>
      <input type="submit" value="display"/></p>
    </form>
''' 

def pt():
    print "</body></html>"


#if __name__ == "__main__":
#    psg()
#    sys.exit(0)


try:
    date = form['date'].value
    type = form['type'].value
except:
    ph()
    pt()
    sys.exit(0)

ph()

pt()
